USE bkcgurx7j7va674tuqsg;
CREATE TABLE Employees (
    Id INT PRIMARY KEY AUTO_INCREMENT,
    Names VARCHAR(100) NOT NULL,
    LastNames VARCHAR(100) NOT NULL,
    BirthDate DATE NOT NULL,
    Email VARCHAR(150) UNIQUE NOT NULL,
    Password VARCHAR(150) UNIQUE NOT NULL,
    Job VARCHAR (100) NOT NULL,
    Gender VARCHAR(50) NOT NULL
);


CREATE TABLE TimeControl(
    Id INT PRIMARY KEY AUTO_INCREMENT,
    DateEntry DATETIME NOT NULL,
    DateExit DATETIME NOT NULL,
    FOREIGN KEY (UserId) REFERENCES Employees(Id)
);